### ISSUE TITLE
Make "coder-toolset" production ready ...

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubbles#20]
The Coder Template in https://github.com/cubbles/coder-template should become a replacement for the existing CoderDevtools.

- [x] integrate webpackage uploader
- [x] adjust docs in gitbook
- [x] integrate manifest validation
- [x] reset repository repository `coder-template` and add `deployCoderTemplate`script to `coder-toolset` repository for pushing latest code from `packages/coder-template` folder to `coder-template` repo
