### ISSUE TITLE
Improvements and TODOs for RTE v4

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/cubbles#47]
### [cubx.core.rte.webpack](https://github.com/cubbles/cubx.core.rte.webpack/tree/one-bundle)
- [ ] Decide if importing templates as HTML imports should be further supported, if not remove support in [CubxComponent](https://github.com/cubbles/cubx.core.rte.webpack/blob/768238f81f1dd5956c599106edaf28dffe2e6640/src/cubxcomponent/CubxComponent.js#L195)
- [ ] Find and implement an alternative to Compounds templates imports. An approach similar to the one employed for elementaries could be used (See examples in [rte.test repo](https://github.com/cubbles/cubx.core.rte.test/tree/rte-one-bundle/src/sample-artifacts/elementary-example)) (i.e., importing the template in a Javascript file, then, transforming the string into a valid HTML template in CompoundComponent)
- [ ] Remove Lodash when possible
- [ ] Check relevance of polyfills
- [ ] Check which external libraries have been updated, and update them
- [ ] Check which external libraries can be imported from npm
- [ ] Use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) when possible
- [ ] Indetifye a way to remove html import caused by DepMrg to fire ready events (See method: [_createScriptForFireEvent](https://github.com/cubbles/cubx.core.rte.webpack/blob/4939921eb91e736a8163c563d0ba2e12a59fa99b/src/core/crc/modules/dependencyManager/depMgr.js#L316))
- [ ] Test https://webpack.js.org/plugins/split-chunks-plugin/ to optimize the loading time of RTE 4
- [ ] Test iframe and iframe-resizer
- [ ] Migrate to es6 (e.g.: CubxComponent as a class, differentiate static methods )
- [ ] Merge one-bundle branch into the master branch
- [ ] Check coverage of unit tests
- [ ] Rename repo to match pakcage.json name 

### [cubx.core.rte.test](https://github.com/cubbles/cubx.core.rte.test/tree/rte-one-bundle)
- [ ] Migrate missing repos from [cubbles-test](https://github.com/cubbles/cubbles-test)
  - [ ] cubx.core.rte.cif-test.dynamic-connection
  - [ ] cubx.core.rte.cif-test.dynamic-cubbles-instances
  - [ ] cubx.core.rte.cif-test.registered-compounds
  - [ ] cubx.core.rte.crc-test.acr-test
  - [ ] cubx.core.rte.crc-test.crc-ready-test
  - [ ] cubx.core.rte.crc-test.iframe-test
  - [ ] cubx.core.rte.crc-test.mutation-based-cubx-startevent-test
  - [ ] cubx.core.rte.cubxpolymer.change-event-test
  - [ ] cubx.core.rte.cubxpolymer-test.cubxready-lifecycle-method-test
- [ ] Merge `rte-one-bundle` branch into the master branch
- [ ] Find a way to make those tests atutomatic
- [ ] Rename repo to match pakcage.json name
