### ISSUE TITLE
CDT: Implement a grunt task for rename an artifact

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubbles#8]
It's really complicated rename an existing component, so it's better use a gruntTask for do it.
The following renames nessecary:
- [x] Rename the artifact in manifest (for all component types)
- [x] Rename the folder of the artifact (for all component types)
- [x] Rename the files in component dir (elementary or compound)
- [x] Rename id in templates (elementary)
- [x] Rename the references in manifest and in files (elementary or compound)
- [x] Rename the component in demo  (elementary or compound)
- [x] Rename the component in docs

Please create a new npm (`cubx-rename-artifact`) package containing the functionality and wrap this package using grunt (`cubx-grunt-rename-artifact`). The newly created repositories should be added to cubbles Zenhub board.
